#  DataBase / TODO : mariaDB ??, datasource ?? ?? ? ??
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/[DB Schema]?autoReconnect=true
    username: [ DB Username ]
    password: [ DB Password ]
    driver-class-name: org.mariadb.jdbc.Driver

  # Spring Live Reload 설정
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  thymeleaf:
    cache: false
    prefix: "file:src/main/resources/templates/"

#  resources:
#    static-locations: "file:src/main/resources/static"



