#  DataBase
spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/todo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  # Spring Live Reload 설정
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  thymeleaf:
    cache: true
    check-template-location: true
    prefix: "file:src/main/resources/templates/"
    suffix: .html
    enabled: true

  messages:
    basename: errors

#  resources:
#    static-locations: "file:src/main/resources/static"

# mybatis mapper 경로 설정
mybatis:
  mapper-locations: classpath:mapper/*.xml
