#  DataBase
spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/todo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  # Spring Live Reload 설정
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  thymeleaf:
    cache: true
    check-template-location: true
    prefix: "file:src/main/resources/templates/"
    suffix: .html
    enabled: true

  # 파일(이미지) 업로드 최대 크기 설정
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB


# mybatis mapper 경로 설정
mybatis:
  mapper-locations: classpath:mapper/*.xml

file:
  upload-path: /Users/an-yeongjun/Desktop/project/image
  stored-path: file:///Users/an-yeongjun/Desktop/project/image/
  default-image: /images/userProfile.png
  allowed-extensions: jpg,jpeg,png
